# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('nfl_team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('qb', models.CharField(max_length=50)),
                ('rb', models.CharField(max_length=50)),
                ('te', models.CharField(max_length=50)),
                ('flex', models.CharField(max_length=50)),
                ('defense', models.CharField(max_length=50)),
                ('kicker', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyfootball.Team'),
        ),
    ]
